### ISSUE TITLE
Line to long

### ISSUE THREAD

**Issue by stonapse64** [Zigazou/rsxmode#1]
HI Zigazou, 

Thank you for this code! I'm trying to use it for a CPC emulator game project (WinAPE) but I'm struggling with it.

First I tried to compile it with the online zasm online compiler at https://k1.spdns.de/cgi-bin/zasm.cgi. Once copied the output file to a dsk and started your loadrsx.bas the emulator returns an "Line too long" error. 

![linetolong](https://user-images.githubusercontent.com/45317767/48971928-f2ec6b00-f020-11e8-8305-7f932f5b8fb6.JPG)

I then compiled it under MacOS with the statement ./zasm --z80 rsxmode.z80 -buow rsxmode.bin. Same result in the emulator. 

I also tried to use the WinAPE assembler to compile it but it produces a lot of errors. As I'm an absolut newbee to machine code I'm a bit helpless at this point. I could sort out some of them but with the following ones I'm really stuck...

line 52-55
    db "SET", 'M' | &80
    db "NOR", 'M' | &80
    db "MOD", 'E' | &80
    db "BOR", 'D' | &80
line 69
    ld b, CLASS_NEAR_ADDRESS | CLASS_ASYNC_EVENT
line 231-233
    rept 23
        nop
    endm

![winape_assembler](https://user-images.githubusercontent.com/45317767/48971987-fdf3cb00-f021-11e8-9fcc-60fcb233f9fd.JPG)

I would really be a happy man if you would have a look into it.

Enjoy your day!
Andreas

**Comment by Zigazou** [comment]
Hi !

The "Line too long" message is usually a Basic message. It means Basic has not been able to load a Basic file.

When transfering files from PC to CPC, it is generally due to a missing 0x1A control code at the end of the file (because AMSDOS does not know about precise file length, it needs this control code in ASCII to tell it stop).

    $ hexdump -C loadrsx.bas
    00000000  31 30 20 27 4c 6f 61 64  20 72 73 78 6d 6f 64 65  |10 'Load rsxmode|
    00000010  2e 62 69 6e 0d 0a 32 30  20 4d 45 4d 4f 52 59 20  |.bin..20 MEMORY |
    00000020  26 39 46 46 46 0d 0a 33  30 20 4c 4f 41 44 22 52  |&9FFF..30 LOAD"R|
    00000030  53 58 4d 4f 44 45 2e 42  49 4e 22 0d 0a 34 30 20  |SXMODE.BIN"..40 |
    00000040  43 41 4c 4c 20 26 41 30  30 30 0d 0a 1a 0d 0a     |CALL &A000.....|
                                                   ^^

I've added the rsxmode.dsk in the repository for you to try.

Does this help ?

**Comment by stonapse64** [comment]
Hi,
I'm watching a growing Mandelbrot... :-) So, yes it helped. Thank you! A lot!

However, your rsxmode.dsk didn't open (I tried with WinAPE, Arnold). 
![notavaliddsk](https://user-images.githubusercontent.com/45317767/49043599-d5a7d000-f1cb-11e8-8f25-bc4d50904989.PNG)

But following your indications I used CPCDiskXP to add an Amsdos-Header to the rsxmode.bin that I'd gotten from ZASM, copied that modified to another dsk and it's working like a charm. 

By the way: in your README.md all URL's in the section

addamsdosheader utility https://github.com/Zigazou/addamsdosheader
cpcxfs (or cpcfs) http://www.cpctech.org.uk/download.html
caprice32 or another emulator https://github.com/ColinPitrat/caprice32

seem to point to https://github.com/Zigazou/rsxmode/blob/master instead of to point to the URL as indicated by the text.

Happy me!
Andreas

**Comment by Zigazou** [comment]
Hi !

I’m glad you found a way !

The rsxmode.dsk file works fine within Caprice32. This is the emulator I’ve used when developping RSXMode. I naively thought the dsk file format would work across all emulators :o)

Thanks for pointing on the incorrect links, that's corrected now.

Regards

Frédéric
